[package]
name = "beezdesktop"
version = "0.1.21"
description = "Beez Desktop Two (SvelteKit + Tauri)"
authors = ["Enrico Zanardo"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/enricozanardo/BeezDesktopTwo"
edition = "2024"
rust-version = "1.90"

[workspace]
members = [".", "native"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
beez-native = { path = "native" }
log = "0.4"
serde_json = "1.0"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
